name: hired_flutter
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  flutter_bloc: ^8.1.2
  injectable: ^2.1.1
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  injectable_generator: ^2.1.5


flutter:
  uses-material-design: true
  fonts:
    - family: DMSans
      fonts:
        - asset: fonts/DMSans-Regular.ttf
        - asset: fonts/DMSans-Medium.ttf
          weight: 600
        - asset: fonts/DMSans-Bold.ttf
          weight: 900

        
    
    
                                      